//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumable
    {
        public Consumable()
        {
            this.ReservationConsumables = new HashSet<ReservationConsumable>();
        }
    
        public int consumableId { get; set; }
        public string name { get; set; }
        public int vendorId { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<ReservationConsumable> ReservationConsumables { get; set; }
    }
}
