//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Reservations = new HashSet<Reservation>();
            this.EventIrregularRepeats = new HashSet<EventIrregularRepeat>();
            this.Locations = new HashSet<Location>();
            this.Options = new HashSet<Option>();
        }
    
        public int eventId { get; set; }
        public string name { get; set; }
        public string owner { get; set; }
        public string organizer { get; set; }
        public int eventStatusId { get; set; }
        public System.DateTime requestDate { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public Nullable<int> attendeeCountDGS { get; set; }
        public Nullable<int> attendeeCountNonDGS { get; set; }
        public Nullable<System.DateTime> repeatEnd { get; set; }
        public Nullable<int> repeatDay { get; set; }
        public Nullable<int> repeatMonth { get; set; }
        public Nullable<int> repeatMonthWeek { get; set; }
        public Nullable<int> repeatMonthlyWeekday { get; set; }
        public Nullable<int> repeatYear { get; set; }
        public Nullable<int> repeatWeek { get; set; }
        public Nullable<int> repeatWeekday { get; set; }
        public string notes { get; set; }
        public Nullable<int> repeatTypeId { get; set; }
        public string repeatIrregular { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modifiedBy { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual EventStatusChoice EventStatusChoice { get; set; }
        public virtual ICollection<EventIrregularRepeat> EventIrregularRepeats { get; set; }
        public virtual RepeatType RepeatType { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Option> Options { get; set; }
    }
}
