//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resdataDAT
    {
        public int Rec_No { get; set; }
        public Nullable<int> Actnumber { get; set; }
        public string Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<System.DateTime> Actualstart { get; set; }
        public Nullable<System.DateTime> Actualend { get; set; }
        public Nullable<System.DateTime> Endtime { get; set; }
        public string Enddate { get; set; }
        public string Actualdate { get; set; }
        public string Actualenddate { get; set; }
    }
}
