//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resdataRAC
    {
        public int Rec_No { get; set; }
        public Nullable<int> Actnumber { get; set; }
        public string Resource { get; set; }
        public Nullable<int> Units { get; set; }
    }
}
