//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resdataREP
    {
        public int Rec_No { get; set; }
        public Nullable<int> Actnumber { get; set; }
        public Nullable<int> Repnumber { get; set; }
        public Nullable<int> Weekendrepeat { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> Weekday { get; set; }
        public Nullable<int> Monday { get; set; }
        public Nullable<int> Tuesday { get; set; }
        public Nullable<int> Wednesday { get; set; }
        public Nullable<int> Thursday { get; set; }
        public Nullable<int> Friday { get; set; }
        public Nullable<int> Saturday { get; set; }
        public Nullable<int> Sunday { get; set; }
        public string Repend { get; set; }
    }
}
