//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationNote
    {
        public int reservationNoteId { get; set; }
        public int reservationId { get; set; }
        public System.DateTime created { get; set; }
        public string note { get; set; }
        public string createdBy { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
