//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation()
        {
            this.ReservationNotes = new HashSet<ReservationNote>();
            this.Locations = new HashSet<Location>();
            this.Options = new HashSet<Option>();
            this.ReservationConsumables = new HashSet<ReservationConsumable>();
            this.Users = new HashSet<User>();
            this.Resources = new HashSet<Resource>();
        }
    
        public int reservationId { get; set; }
        public int eventId { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string createdBy { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<int> attendeeCountDGS { get; set; }
        public Nullable<int> attendeeCountNonDGS { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<ReservationNote> ReservationNotes { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Option> Options { get; set; }
        public virtual ICollection<ReservationConsumable> ReservationConsumables { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }
    }
}
