//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserFoodProfiles = new HashSet<UserFoodProfile>();
            this.Reservations = new HashSet<Reservation>();
            this.Options = new HashSet<Option>();
        }
    
        public int userId { get; set; }
        public string loginName { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string shortName { get; set; }
        public string company { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<UserFoodProfile> UserFoodProfiles { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<Option> Options { get; set; }
    }
}
