//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFoodProfileDietaryRestriction
    {
        public int userFoodProfileDietaryRestrictionId { get; set; }
        public Nullable<int> userFoodProfileId { get; set; }
        public Nullable<int> dietaryRestrictionId { get; set; }
    
        public virtual DietaryRestriction DietaryRestriction { get; set; }
        public virtual UserFoodProfile UserFoodProfile { get; set; }
    }
}
