//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFoodProfile
    {
        public UserFoodProfile()
        {
            this.UserFoodProfileDietaryRestrictions = new HashSet<UserFoodProfileDietaryRestriction>();
        }
    
        public int userFoodProfileId { get; set; }
        public int userId { get; set; }
        public string likes { get; set; }
        public string dislikes { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<UserFoodProfileDietaryRestriction> UserFoodProfileDietaryRestrictions { get; set; }
    }
}
