//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorContact
    {
        public int vendorContactId { get; set; }
        public int vendorId { get; set; }
        public int contactId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
