//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ReservationLocation
    {
        public int locationId { get; set; }
        public string name { get; set; }
        public int maxOccupancy { get; set; }
        public int reservationLocationId { get; set; }
        public int reservationId { get; set; }
        public int Expr1 { get; set; }
        public int Expr2 { get; set; }
        public int eventId { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string createdBy { get; set; }
        public string modifiedBy { get; set; }
    }
}
